canonical/zookeeper-operator

- lib/charms/kafka/v0/kafka_snap.py
- lib/charms/zookeeper/v0/client.py
- lib/charms/zookeeper/v0/cluster.py
- poetry.lock
- pyproject.toml
- requirements.txt
- src/charm.py
- tests/integration/__init__.py
- tests/integration/scaling_helpers.py
- tests/integration/test_charm.py
- tests/integration/test_scaling.py
- tests/unit/test_client.py
- tox.ini
- `fix: resolve issue with new quorum not being met fast enough` - Solved by adding a `retry` to leader finding, and by continuing loops over expected members in case of a connection `KazooTimeoutError`
- If quorum leader went down, the Juju leader would be unable to find the new quorum leader because they hadn't yet been elected. We don't want to just `event.defer()`, as it would wait for the next `update-status` event before running, causing downtime
- A small retry helps this without adding too much latency
- Reloading `zk.server_members` from a property ensures that new member changes are found
- `fix: resolve issue where units ran out of defer events during start-up and getting stuck`
- While waiting for the Juju leader to add lower-id units, ready-to-start units would run out of …
> feat: integration tests for ZK scaling

- lib/charms/kafka/v0/kafka_snap.py
- lib/charms/rolling_ops/v0/rollingops.py
- lib/charms/zookeeper/v0/client.py
- lib/charms/zookeeper/v0/cluster.py
- lib/charms/zookeeper/v0/zookeeper_provider.py
- metadata.yaml
- src/charm.py
- tests/unit/test_zookeeper_provider.py
- tox.ini
This is an intermediary PR, so please skip RollingOps and please focus on `client.py` and `zookeeper_provider.py` changes.
This is also my first time doing a client relation, so please let me know if I've done a really silly pattern.
- `feat: add provider relation`. This manages the creation and removal of users from ZK auth config
- `feat: add rolling ops`. This will eventually be used for rolling restarts on `relation_joined/broken` events when new clients alter the relations
- `test: unit tests for znode methods and provider library`
- Implement Rolling Restarts of ZK units upon requisite relation events, updating their `JAAS` file
- Integration tests with a dummy charm. Unit test coverage is pretty strong, but I'm sure there are issues I've missed having not yet deployed it, so I will …
> feat: add provider relation auth data management for clients 

- .github/workflows/ci.yaml
- lib/charms/zookeeper/v0/client.py
- lib/charms/zookeeper/v0/cluster.py
- src/charm.py
- tests/integration/test_scaling.py
- tests/unit/test_client.py
- tox.ini
- `fix: units no longer need to init at '0'`
- Previously ZK would fail after a redeploy, as it couldn't find unit 0 in the relation data
- Added `lowest_unit_id` search, so that if unit 3,4,5 is deployed, 3 will be found lowest and start 
- `fix: update faulty regex not looking for '0'`
- This didn't cause too many issues, but meant that the relation data would update unit '1' instead of unit '10'
> fix: resolve bug that stopped re-deployed zookeeper apps in the same model from starting

- .github/workflows/release.yaml
The CD pipeline needs to pass testing so it is automatically released.
> Update release pipeline

- tests/integration/helpers.py
- tests/integration/test_provider.py
This PR includes a check that verifies that ACL permissions are granted when Zookeeper relates with another application.
> test: check that ACL are set correctly when you relate with an application

- lib/charms/zookeeper/v0/client.py
- src/charm.py
- src/provider.py
- tests/unit/test_provider.py
- This was mostly an omission from previous SSL PR
- Also added an `ssl` field, to inform clients that they should be using an SSL port. Intended usage of this might be something like:
- `if 'ssl' in relation.data and not self.signed_cert: BlockedStatus` 
- When ZK and a client was deployed and related simultaneously, ZK would attempt to handle the `client_relation` events before properly starting up
- This caused several issues, but mostly it locked up due to attempting to find quorum leader, before quorum had been established
- Fixed by checking for `quorum` relation data flag before handling provider relation events
> fix: ensure provided port is updated if SSL is enabled

- src/charm.py
- src/cluster.py
- src/config.py
- src/provider.py
- tests/unit/test_provider.py
- Update to align with other database charm relation interfaces using the same flag
- Previous implementation mistakenly skipped the `portUnification`+`sslQuorum` step when switching to SSL quorum encryption, sometimes resulting in loss of quorum
- This had a knock-on effect, where only a single-server quorum was left, and when a client related to the ZK app, that server would restart and not be part of a quorum 
- Fixed by setting unit + app level relation data checking that all units are at the correct stage of an encryption change, before doing anything else
- Previous implementation mistakenly overwrote the dynamic property set in `zookeeper.properties` to set new SSL-specific config, sometimes resulting in loss of quorum
- This resulted in servers sometimes not being aware of other …
> chore: ensure portUnification+sslQuorum step is not missed

- requirements.txt
- tests/unit/test_client.py
- tests/unit/test_cluster.py
- tests/unit/test_config.py
- tests/unit/test_provider.py
- tests/unit/test_tls.py
- Keeping consistency for ZK/Kafka charms, with easier test writing and deeper features made available by `pytest`
- There are no actual test diffs here. It's just using `pytest` instead of `unittest`
> chore: use pytest for all unit-tests

- src/charm.py
- src/config.py
- src/provider.py
- src/tls.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
- tests/unit/test_config.py
- tests/unit/test_provider.py
- Due to active development, there were no unittests for `charm.py`. These have been added
- Added additional `cluster.py` and `tls.py` tests to add coverage for new features
- Please focus on `tests/unit/test_charm.py`
- There are a lot of tests, so most help would be whether any were implemented incorrectly from an `ops.testing` standpoint
> test: introduce charm.py unittest coverage

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- pyproject.toml
- requirements.txt
- src/charm.py
- src/cluster.py
- src/config.py
- src/provider.py
- src/tls.py
- tests/unit/test_charm.py
- tests/unit/test_client.py
- tests/unit/test_cluster.py
- tests/unit/test_config.py
- tests/unit/test_provider.py
- tests/unit/test_tls.py
- tox.ini
- Fixes bug with how sans were being used
- Sans containing host DNS, host IP
- Subject name of host IP
- Had to be done to fix failing lint tests
- To fix bug with release of version `3.0+`
Focus review on commits c00f9fbe73c9842f7c50402a141e36e144779299 and efa1b937743d2e810dab1abc9198d318673832e3 to save headache of tls lib updates and `ruff` reformat
> feat: working quorum and client hostname verification

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- charmcraft.yaml
- metadata.yaml
- pyproject.toml
- tests/integration/app-charm/charmcraft.yaml
- tests/integration/app-charm/metadata.yaml
> fix: bump to 22.04, use py310

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- lib/charms/zookeeper/v0/client.py
- metadata.yaml
- src/charm.py
- src/config.py
- src/literals.py
- src/snap.py
- src/tls.py
- src/utils.py
- tests/integration/helpers.py
- tests/unit/test_charm.py
- tests/unit/test_config.py
- Updates the snap version to `edge` channel
- Ensures files written to `$SNAP_COMMON` are owned by `snap_daemon` user
> chore: switch to 3.6/edge snap for non-root user

- lib/charms/zookeeper/v0/client.py
- src/charm.py
- src/cluster.py
- src/provider.py
- src/tls.py
- tests/unit/test_charm.py
- tests/unit/test_client.py
- tests/unit/test_cluster.py
- tests/unit/test_config.py
- tests/unit/test_provider.py
- tests/unit/test_tls.py
Bundles should be more reliable.
- Probably the most helpful change with minimal overhead. Shout out @welpaolo for the idea!
- This helps ensure client applications get refreshed data if, god forbid, events get stuck without being woken up by a `relation-changed` from a peer-unit
- It also helps with quorum stability during scaling operations
- To avoid issues with bundles attempting a relation during a cluster initialisation 
- TLS relations can be triggered if ever the cluster is no longer scaling/adding units
- Client relations can be triggered if the cluster is not scaling/adding (`stable`) and not installing upgrading to TLS (`ready`)
- Generally helpful, they were needed to solve the problem, might as well keep them there
- This ensures that units always are loaded with the most …
> refactor: block external relation events until cluster has initialised

- charmcraft.yaml
Packing zk fails with:
```
run pkg_config fail: Could not run `"pkg-config" "--libs" "--cflags" "openssl"`
The pkg-config command could not be found.
Most likely, you need to install a pkg-config package for your OS.
Try `apt install pkg-config`, or `yum install pkg-config`,
or `pkg install pkg-config`, or `apk add pkgconfig` depending on your distribution.
```
[charmcraft-20230324-115735.615985.log](https://github.com/canonical/zookeeper-operator/files/11064399/charmcraft-20230324-115735.615985.log)
Add deps to `charmcraft.yaml`. With those, packing succeeds.
Recently we had to [do the same with traefik](https://github.com/canonical/traefik-k8s-operator/pull/150). h/t @rbarry82
> Add tls deps to `charmcraft.yaml`

- poetry.lock
- pyproject.toml
- requirements.txt
- src/provider.py
- src/tls.py
- tests/integration/helpers.py
- tests/integration/test_scaling.py
- tox.ini
- Gets used in `tox -e lint` for simplicity (no need to add a new command)
- If you want to have type warnings appear normally during development, if you're using VSCode as your editor, ensure you have the `ms-python.python` extension, and add the following to your `settings.json`:
```
"python.analysis.extraPaths": ["./lib"],
"typeCheckingMode": "basic"
```
> feat/style: introduce pyright, tidy up errors

- .jujuignore
- poetry.lock
- pyproject.toml
- src/charm.py
- src/cluster.py
- src/config.py
- src/provider.py
- src/tls.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
- tests/unit/test_config.py
- tests/unit/test_provider.py
- tests/unit/test_tls.py
- Tracking all the different object specific copies of `peer_relation` was a pain
- Now it's all stuck within `charm.py` and accessed from outside using `self.charm.peer_relation` and `self.charm.app/unit_peer_data`
- Currently loads of stuff was in there
- Now it should be slightly faster to deploy
> refactor: extend jujuignore, add typehints, remove excess peer_relations

- metadata.yaml
- src/charm.py
- src/config.py
- src/literals.py
- src/utils.py
- tests/unit/test_charm.py
- Following recommendations found under `dataLogDir` from the [ZooKeeper Administration Guide](https://zookeeper.apache.org/doc/r3.1.2/zookeeperAdmin.html#sc_advancedConfiguration)
- Intent is to have a persistent storage source for all necessary back-up data
> feat: add snapshot storage

- src/alert_rules/prometheus/high_file_descriptors.rule
- src/alert_rules/prometheus/jmx_missing.rule
- src/alert_rules/prometheus/jvm_filling.rule
- src/alert_rules/prometheus/outstanding_requests.rule
- src/alert_rules/prometheus/zk_avg_lantecy.rule
- src/alert_rules/prometheus/zookeeper_metrics.rules
This PR is to provide some sensible defaults for the base alerting rule for Zookeeper
Note: The label `juju_charm!=".*"` in every rule is to workaround a bug currently found in COS, where the `juju_charm` is applied to the rules but not to the metrics. See more details [here](https://github.com/canonical/grafana-agent-k8s-operator/issues/190)
> [DPE-2010] Alerting rules for Zookeeper VM

- src/utils.py
- tests/unit/test_utils.py
Ignore empty keys when building the map_env dict
> Fix invalid etc env (fix #73)

- lib/charms/zookeeper/v0/client.py
- tests/unit/test_client.py
Tied to [DPE-2244](https://warthogs.atlassian.net/browse/DPE-2244)
Adds version getter to `client` lib. This can be used both on the ZooKeeper and Kafka charms to solve dependencies.
[DPE-2244]: https://warthogs.atlassian.net/browse/DPE-2244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add version getter

- src/literals.py
- src/snap.py
- src/tls.py
- tests/integration/test_tls.py
Depends on https://github.com/canonical/charmed-zookeeper-snap/pull/13
Fixes https://github.com/canonical/zookeeper-operator/issues/69
- Was originally installed to use `keytool`
- Now usable through `charmed-zookeeper.keytool`
> DPE-1965/DPE-2065 - chore: remove openjdk

- src/utils.py
`SERVER_JVMFLAGS` value was being created without leading and trailing quotation marks, which would make the value unusable when sourcing the file.
```
/etc/environment
SERVER_JVMFLAGS=-Dzookeeper.requireClientAuthScheme=sasl . . .
SERVER_JVMFLAGS="-Dzookeeper.requireClientAuthScheme=sasl . . . "
```
> [DPE-2623] chore: fix environment file creation

- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/upgrade.py
- src/charm.py
- src/cluster.py
- src/config.py
- src/provider.py
- src/snap.py
- src/tls.py
- tests/integration/ha/helpers.py
- tests/integration/ha/test_ha.py
- tests/integration/test_upgrade.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
- tests/unit/test_config.py
- tests/unit/test_provider.py
- tests/unit/test_tls.py
- tests/unit/test_upgrade.py
- `on_install` - Units set `ip`, `hostname` and `fqdn` to their unit peer data
- The contents of these fields for all peer-related units are written to each unit's `/etc/hosts` for address resolution
- ZooKeeper server strings now look similar to: 
- Related client applications still receive the `ip` address as normal 
- After a unit's IP changes underneath it, the unit gets a `config-changed` event
- While handling this event, units attempt to update their `ip` + `fqdn` in their unit peer data, in case their IP changed
- Other units gets `relation-changed`, and restart, because the expected contents of their `/etc/hosts` file has now changed
> DPE-2514 - test: add self-healing after network cut + ip change HA test

- .github/workflows/ci.yaml
- Ensures only one test runs at any time, avoiding CPU limit / timeouts etc
- Pytest Operator cleanup was challenging after the LXD model was messed with during HA tests
- `--keep-model` allows Github to clean up resources after test completion
> cicd: keep model in ha test, max-parallel=1

- src/events/provider.py
- src/managers/config.py
- src/managers/quorum.py
- tests/integration/test_provider.py
- tests/unit/test_provider.py
- tests/unit/test_quorum.py
- Mistake from the refactor meant that on `relation-broken` events, the `chroot` from the broken Application would still exist, with it's zNodes surviving the break
- Removing a Kafka relation, then re-relating, would persist the original ACLs (e.g `relation-6`) on child nodes (e.g `/kafka/config/users`) sharing the same parent (e.g `/kafka`)
- This meant that the related application couldn't authenticate to the new zNodes
> fix: properly remove old zNodes during relation-broken

- src/events/upgrade.py
- src/managers/quorum.py
- tests/unit/test_quorum.py
- tests/unit/test_upgrade.py
- Found when relating applications to ZooKeeper too quickly before cluster init, ZooKeeper will read an empty value for `client.chroot` and attempt to add it, resulting in a `NodeExistsError` from Kazoo
- Now, we skip setting anything if `client.chroot` does not exist
- Also made the chroot logging `INFO` level, for more clarity of what's happening
- Motivation for change found in https://github.com/canonical/zookeeper-k8s-operator/pull/60#discussion_r1464336395
> fix: skip empty chroot adding 

- src/charm.py
- src/events/upgrade.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
- tests/unit/test_upgrade.py
- Moved to dedicated method
- Added setting of `truststore-password` unit-data, which was not present in older revisions
- `config_changed` setting of config items is now skipped, avoiding issues with missing new relation-data items
- Juju status setting should now be skipped on `update-status`, meaning that the charm will stay `BlockedStatus` if upgrade failed
> DPE-3364 DPE-3563 fix: skip relation-changed if upgrading

- .github/workflows/ci.yaml
- src/managers/config.py
- tests/integration/ha/test_ha.py
- tests/integration/test_charm.py
- tests/integration/test_password_rotation.py
- tests/integration/test_tls.py
- tests/integration/test_upgrade.py
- tox.ini
Adds missing tests file. Addresses #117
- Testing zookeeper access is done on `test_provider.py`.
Also ports change on pebble layer declaration.
> [DPE-3599] Add missing tests

- .github/workflows/ci.yaml
- metadata.yaml
- src/charm.py
- src/core/cluster.py
- src/core/models.py
- src/literals.py
- src/managers/quorum.py
- tests/integration/ha/test_scaling.py
- tests/unit/test_charm.py
- tests/unit/test_cluster.py
- tests/unit/test_quorum.py
- tox.ini
Fixes https://github.com/canonical/zookeeper-operator/issues/140. Probably.
- The theory for the bug is that at some point, machines are rotated on the Juju cloud, including the Juju controller machine. When this happens, a unit gets `LeaderElected`, and proceeds to update the quorum. However for whatever reason, it is unable to find any peer units. Thinking they are alone, the new leader promptly removes every other unit from the quorum, without recovery
- The fix ensures that on `relation-departed`, every non-departing unit will attempt to remove the departing unit from the quorum
- This is slightly more resilient against losing Juju or Quorum leaders, as they will be removed in advance of the cluster losing a stable quorum. For additional reading, see the [ZooKeeper docs for …
> [DPE-4183] - fix: only handle quorum removal on relation-departed

- src/managers/config.py
It seems like our ZooKeeper upgrade to 3.9 changed the default cipher used for encryption.
charmed-zookeeper 3.8:
```
nmap --script ssl-enum-ciphers -p 2182 10.28.199.223
Starting Nmap 7.95 ( https://nmap.org ) at 2024-09-24 10:48 CEST
Nmap scan report for 10.28.199.223
Host is up (0.00012s latency).
PORT     STATE SERVICE
2182/tcp open  cgn-stat
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|     compressors:
|       NULL
| …
```
> [DPE-5549] Enable TLS v1.2 for client communication

- actions.yaml
- metadata.yaml
- src/charm.py
- src/core/cluster.py
- src/core/models.py
- src/core/stubs.py
- src/core/workload.py
- src/events/backup.py
- src/events/provider.py
- src/literals.py
- src/managers/backup.py
- src/managers/config.py
- src/managers/quorum.py
- tests/integration/test_backup.py
- tests/unit/scenario/test_backup.py
- tests/unit/test_charm.py
- tests/unit/test_config.py
- tests/unit/test_quorum.py
- tests/unit/test_upgrade.py
This PR implements the flow for restoring a ZooKeeper snapshot.
- Add retry configuration to S3 resource in case of flaky network.
- Recursively update ACLs if the requested zNode already exists
- Write a `client-jaas.cfg` file to streamline a little bit the process of accessing the ZK cluster within the machine.
- Update ACLs to only let the superuser access the path for zNodes that are not currently requested by a related client application
This flow can be used to bootstrap a new cluster using seeded data. Upon relating with a new client application, let's say, Kafka, here is what is going to happen:
- the ACLs for `/kafka` and its subnodes will be updated to the new relation, if it already existed
- Kafka's relation flow will recreate its `admin` and `sync` users, but, we will keep …
> [DPE-5218] Implement restore flow

- src/managers/config.py
- tests/unit/test_config.py
Changes:
- Preserve other /etc/hosts records on update
> fix: don't erase previous record from /etc/hosts

- .readthedocs.yaml
Trying to fix ReadTheDocs builds fail with warning messages for too shallow clone, probably caused by the unshallow command being used at a worng stage of the process.
> [Docs] Fix the docs build error for shallow clone

- docs/conf.py
- docs/content/explanation/ha.md
- docs/content/how-to/deploy.md
- docs/content/how-to/index.md
- docs/content/tutorial/cleanup.md
- docs/content/tutorial/deploy.md
- docs/content/tutorial/index.md
- docs/content/tutorial/integrate.md
- docs/index.md
Charmed operator term is replaced with a shorter one - charm. As recommended by Juju team. Also, that works better for web portal titles - making them shorter and easier to fit into the template.
> Docs: Adjust terminology for charmed operators
